version: 2
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
jobs:
  build:
    docker:
      - image: circleci/node:8.7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
      - run:
          name: fmt
          command: npm run fmt
      - run:
          name: test
          command: npm run cicoverage
